/**
 * generated by Xtext 2.15.0
 */
package org.xtext.whileLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Not</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.whileLanguage.ExprNot#getE <em>E</em>}</li>
 *   <li>{@link org.xtext.whileLanguage.ExprNot#getE2 <em>E2</em>}</li>
 * </ul>
 *
 * @see org.xtext.whileLanguage.WhileLanguagePackage#getExprNot()
 * @model
 * @generated
 */
public interface ExprNot extends EObject
{
  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>E</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference.
   * @see #setE(ExprEq)
   * @see org.xtext.whileLanguage.WhileLanguagePackage#getExprNot_E()
   * @model containment="true"
   * @generated
   */
  ExprEq getE();

  /**
   * Sets the value of the '{@link org.xtext.whileLanguage.ExprNot#getE <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E</em>' containment reference.
   * @see #getE()
   * @generated
   */
  void setE(ExprEq value);

  /**
   * Returns the value of the '<em><b>E2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>E2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>E2</em>' containment reference.
   * @see #setE2(ExprEq)
   * @see org.xtext.whileLanguage.WhileLanguagePackage#getExprNot_E2()
   * @model containment="true"
   * @generated
   */
  ExprEq getE2();

  /**
   * Sets the value of the '{@link org.xtext.whileLanguage.ExprNot#getE2 <em>E2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E2</em>' containment reference.
   * @see #getE2()
   * @generated
   */
  void setE2(ExprEq value);

} // ExprNot
