/**
 * generated by Xtext 2.15.0
 */
package org.xtext.whileLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.whileLanguage.Function#getD <em>D</em>}</li>
 * </ul>
 *
 * @see org.xtext.whileLanguage.WhileLanguagePackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends EObject
{
  /**
   * Returns the value of the '<em><b>D</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>D</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>D</em>' containment reference.
   * @see #setD(Definition)
   * @see org.xtext.whileLanguage.WhileLanguagePackage#getFunction_D()
   * @model containment="true"
   * @generated
   */
  Definition getD();

  /**
   * Sets the value of the '{@link org.xtext.whileLanguage.Function#getD <em>D</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>D</em>' containment reference.
   * @see #getD()
   * @generated
   */
  void setD(Definition value);

} // Function
