/**
 * generated by Xtext 2.14.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.WhileLanguageRuntimeModule;
import org.xtext.WhileLanguageStandaloneSetup;
import org.xtext.ide.WhileLanguageIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class WhileLanguageIdeSetup extends WhileLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    WhileLanguageRuntimeModule _whileLanguageRuntimeModule = new WhileLanguageRuntimeModule();
    WhileLanguageIdeModule _whileLanguageIdeModule = new WhileLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_whileLanguageRuntimeModule, _whileLanguageIdeModule));
  }
}
