/*
 * generated by Xtext 2.14.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WhileLanguageStandaloneSetup extends WhileLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new WhileLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
