/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.wh.wh.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.comp.wh.wh.ExprEq;
import org.xtext.comp.wh.wh.ExprNot;
import org.xtext.comp.wh.wh.WhPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expr Not</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.wh.impl.ExprNotImpl#getHasNot <em>Has Not</em>}</li>
 *   <li>{@link org.xtext.comp.wh.wh.impl.ExprNotImpl#getExpr_eq <em>Expr eq</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExprNotImpl extends MinimalEObjectImpl.Container implements ExprNot
{
  /**
   * The default value of the '{@link #getHasNot() <em>Has Not</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHasNot()
   * @generated
   * @ordered
   */
  protected static final String HAS_NOT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHasNot() <em>Has Not</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHasNot()
   * @generated
   * @ordered
   */
  protected String hasNot = HAS_NOT_EDEFAULT;

  /**
   * The cached value of the '{@link #getExpr_eq() <em>Expr eq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpr_eq()
   * @generated
   * @ordered
   */
  protected ExprEq expr_eq;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExprNotImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WhPackage.Literals.EXPR_NOT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getHasNot()
  {
    return hasNot;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHasNot(String newHasNot)
  {
    String oldHasNot = hasNot;
    hasNot = newHasNot;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_NOT__HAS_NOT, oldHasNot, hasNot));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExprEq getExpr_eq()
  {
    return expr_eq;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpr_eq(ExprEq newExpr_eq, NotificationChain msgs)
  {
    ExprEq oldExpr_eq = expr_eq;
    expr_eq = newExpr_eq;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_NOT__EXPR_EQ, oldExpr_eq, newExpr_eq);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpr_eq(ExprEq newExpr_eq)
  {
    if (newExpr_eq != expr_eq)
    {
      NotificationChain msgs = null;
      if (expr_eq != null)
        msgs = ((InternalEObject)expr_eq).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhPackage.EXPR_NOT__EXPR_EQ, null, msgs);
      if (newExpr_eq != null)
        msgs = ((InternalEObject)newExpr_eq).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhPackage.EXPR_NOT__EXPR_EQ, null, msgs);
      msgs = basicSetExpr_eq(newExpr_eq, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_NOT__EXPR_EQ, newExpr_eq, newExpr_eq));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WhPackage.EXPR_NOT__EXPR_EQ:
        return basicSetExpr_eq(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WhPackage.EXPR_NOT__HAS_NOT:
        return getHasNot();
      case WhPackage.EXPR_NOT__EXPR_EQ:
        return getExpr_eq();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WhPackage.EXPR_NOT__HAS_NOT:
        setHasNot((String)newValue);
        return;
      case WhPackage.EXPR_NOT__EXPR_EQ:
        setExpr_eq((ExprEq)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WhPackage.EXPR_NOT__HAS_NOT:
        setHasNot(HAS_NOT_EDEFAULT);
        return;
      case WhPackage.EXPR_NOT__EXPR_EQ:
        setExpr_eq((ExprEq)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WhPackage.EXPR_NOT__HAS_NOT:
        return HAS_NOT_EDEFAULT == null ? hasNot != null : !HAS_NOT_EDEFAULT.equals(hasNot);
      case WhPackage.EXPR_NOT__EXPR_EQ:
        return expr_eq != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (hasNot: ");
    result.append(hasNot);
    result.append(')');
    return result.toString();
  }

} //ExprNotImpl
