/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.wh.wh;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Commands</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.wh.Commands#getC <em>C</em>}</li>
 *   <li>{@link org.xtext.comp.wh.wh.Commands#getC2 <em>C2</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.wh.wh.WhPackage#getCommands()
 * @model
 * @generated
 */
public interface Commands extends EObject
{
  /**
   * Returns the value of the '<em><b>C</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.comp.wh.wh.Command}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>C</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>C</em>' containment reference list.
   * @see org.xtext.comp.wh.wh.WhPackage#getCommands_C()
   * @model containment="true"
   * @generated
   */
  EList<Command> getC();

  /**
   * Returns the value of the '<em><b>C2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.comp.wh.wh.Command}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>C2</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>C2</em>' containment reference list.
   * @see org.xtext.comp.wh.wh.WhPackage#getCommands_C2()
   * @model containment="true"
   * @generated
   */
  EList<Command> getC2();

} // Commands
