/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.wh.wh;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.wh.Command#getNop <em>Nop</em>}</li>
 *   <li>{@link org.xtext.comp.wh.wh.Command#getAssign <em>Assign</em>}</li>
 *   <li>{@link org.xtext.comp.wh.wh.Command#getWh <em>Wh</em>}</li>
 *   <li>{@link org.xtext.comp.wh.wh.Command#getFor <em>For</em>}</li>
 *   <li>{@link org.xtext.comp.wh.wh.Command#getIf <em>If</em>}</li>
 *   <li>{@link org.xtext.comp.wh.wh.Command#getForeach <em>Foreach</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.wh.wh.WhPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
  /**
   * Returns the value of the '<em><b>Nop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nop</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nop</em>' attribute.
   * @see #setNop(String)
   * @see org.xtext.comp.wh.wh.WhPackage#getCommand_Nop()
   * @model
   * @generated
   */
  String getNop();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.wh.Command#getNop <em>Nop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nop</em>' attribute.
   * @see #getNop()
   * @generated
   */
  void setNop(String value);

  /**
   * Returns the value of the '<em><b>Assign</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assign</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assign</em>' containment reference.
   * @see #setAssign(Assign)
   * @see org.xtext.comp.wh.wh.WhPackage#getCommand_Assign()
   * @model containment="true"
   * @generated
   */
  Assign getAssign();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.wh.Command#getAssign <em>Assign</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assign</em>' containment reference.
   * @see #getAssign()
   * @generated
   */
  void setAssign(Assign value);

  /**
   * Returns the value of the '<em><b>Wh</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Wh</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wh</em>' containment reference.
   * @see #setWh(While)
   * @see org.xtext.comp.wh.wh.WhPackage#getCommand_Wh()
   * @model containment="true"
   * @generated
   */
  While getWh();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.wh.Command#getWh <em>Wh</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wh</em>' containment reference.
   * @see #getWh()
   * @generated
   */
  void setWh(While value);

  /**
   * Returns the value of the '<em><b>For</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>For</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>For</em>' containment reference.
   * @see #setFor(For)
   * @see org.xtext.comp.wh.wh.WhPackage#getCommand_For()
   * @model containment="true"
   * @generated
   */
  For getFor();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.wh.Command#getFor <em>For</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>For</em>' containment reference.
   * @see #getFor()
   * @generated
   */
  void setFor(For value);

  /**
   * Returns the value of the '<em><b>If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>If</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>If</em>' containment reference.
   * @see #setIf(If)
   * @see org.xtext.comp.wh.wh.WhPackage#getCommand_If()
   * @model containment="true"
   * @generated
   */
  If getIf();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.wh.Command#getIf <em>If</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If</em>' containment reference.
   * @see #getIf()
   * @generated
   */
  void setIf(If value);

  /**
   * Returns the value of the '<em><b>Foreach</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Foreach</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Foreach</em>' containment reference.
   * @see #setForeach(Foreach)
   * @see org.xtext.comp.wh.wh.WhPackage#getCommand_Foreach()
   * @model containment="true"
   * @generated
   */
  Foreach getForeach();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.wh.Command#getForeach <em>Foreach</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Foreach</em>' containment reference.
   * @see #getForeach()
   * @generated
   */
  void setForeach(Foreach value);

} // Command
