/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.wh.wh;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.wh.Expr#getExpr_and <em>Expr and</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.wh.wh.WhPackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr and</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr and</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr and</em>' containment reference.
   * @see #setExpr_and(ExprAnd)
   * @see org.xtext.comp.wh.wh.WhPackage#getExpr_Expr_and()
   * @model containment="true"
   * @generated
   */
  ExprAnd getExpr_and();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.wh.Expr#getExpr_and <em>Expr and</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr and</em>' containment reference.
   * @see #getExpr_and()
   * @generated
   */
  void setExpr_and(ExprAnd value);

} // Expr
