/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.wh.wh;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Eq</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.wh.ExprEq#getExpr_left <em>Expr left</em>}</li>
 *   <li>{@link org.xtext.comp.wh.wh.ExprEq#getExpr_right <em>Expr right</em>}</li>
 *   <li>{@link org.xtext.comp.wh.wh.ExprEq#getSym <em>Sym</em>}</li>
 *   <li>{@link org.xtext.comp.wh.wh.ExprEq#getLexpr <em>Lexpr</em>}</li>
 *   <li>{@link org.xtext.comp.wh.wh.ExprEq#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.wh.wh.WhPackage#getExprEq()
 * @model
 * @generated
 */
public interface ExprEq extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr left</em>' containment reference.
   * @see #setExpr_left(ExprSimple)
   * @see org.xtext.comp.wh.wh.WhPackage#getExprEq_Expr_left()
   * @model containment="true"
   * @generated
   */
  ExprSimple getExpr_left();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.wh.ExprEq#getExpr_left <em>Expr left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr left</em>' containment reference.
   * @see #getExpr_left()
   * @generated
   */
  void setExpr_left(ExprSimple value);

  /**
   * Returns the value of the '<em><b>Expr right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr right</em>' containment reference.
   * @see #setExpr_right(ExprSimple)
   * @see org.xtext.comp.wh.wh.WhPackage#getExprEq_Expr_right()
   * @model containment="true"
   * @generated
   */
  ExprSimple getExpr_right();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.wh.ExprEq#getExpr_right <em>Expr right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr right</em>' containment reference.
   * @see #getExpr_right()
   * @generated
   */
  void setExpr_right(ExprSimple value);

  /**
   * Returns the value of the '<em><b>Sym</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sym</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sym</em>' attribute.
   * @see #setSym(String)
   * @see org.xtext.comp.wh.wh.WhPackage#getExprEq_Sym()
   * @model
   * @generated
   */
  String getSym();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.wh.ExprEq#getSym <em>Sym</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sym</em>' attribute.
   * @see #getSym()
   * @generated
   */
  void setSym(String value);

  /**
   * Returns the value of the '<em><b>Lexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lexpr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lexpr</em>' containment reference.
   * @see #setLexpr(LExpr)
   * @see org.xtext.comp.wh.wh.WhPackage#getExprEq_Lexpr()
   * @model containment="true"
   * @generated
   */
  LExpr getLexpr();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.wh.ExprEq#getLexpr <em>Lexpr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lexpr</em>' containment reference.
   * @see #getLexpr()
   * @generated
   */
  void setLexpr(LExpr value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expr)
   * @see org.xtext.comp.wh.wh.WhPackage#getExprEq_Expr()
   * @model containment="true"
   * @generated
   */
  Expr getExpr();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.wh.ExprEq#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expr value);

} // ExprEq
