/*
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.wh


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class WhRuntimeModule extends AbstractWhRuntimeModule {
}
